### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by tunnckoCore** [ehmicky/get-node#1]
The error is happening no matter the chosen node version.

```
❯ nve 12 foo.js
EXDEV: cross-device link not permitted, rename '/tmp/get-node-12.8.0265305VEGYnMd8ahw' -> '/home/charlike/.cache/nve/12.8.0/node'
❯ nve 10 foo.js
EXDEV: cross-device link not permitted, rename '/tmp/get-node-10.16.226957Vjk86vu96oy0' -> '/home/charlike/.cache/nve/10.16.2/node'
```

I only have one SSD on the machine which is ArchLinux with Linux kernel 4.19.

I usually use `nvm`, is it counts as "global nodejs install"? I don't think so. That's why I also installed globally nodejs through AUR (which seems to be v11.15).

Btw, are we able to provide `--require` hook? That would be insanely cool! 

edit: Ha, interesting auto-labeler. What you are using on that repo? Doesn't seem like a bot, because it uses the author? Or is it already builtin within GitHub when using issue/pr templates?

**Comment by ehmicky** [comment]
This should be fixed in [`nve@1.1.5`](https://github.com/ehmicky/nve/releases/tag/1.1.5). Could you please confirm it now works?

**Comment by tunnckoCore** [comment]
Cool, thanks. I'll try later today.

**Comment by ehmicky** [comment]
Is it working now?

**Comment by tunnckoCore** [comment]
Seems okay, yea. Thanks and sorry for the delay. :)

**Comment by ehmicky** [comment]
@all-contributors please add @tunnckoCore for reporting this bug!
