### ISSUE TITLE
Allow choosing architechture (32bit vs 64bit)

### ISSUE THREAD

**Issue by papb** [ehmicky/get-node#3]
**Which problem is this feature request solving?**

I have a 64-bit machine but due to some unfortunate legacy issues I need to use an old 32-bit version of node for a specific task. For the rest of my tasks I like to use newer versions such as 12 and the 64-bit version.

**Describe the solution you'd like**

I would like to be able to run something like:

```bash
$ nve --32bit 8 node -p 'process.arch'
ia32
```

Currently I can only get `x64`.

It is also important for me to be able to call `nve --32bit 8 npm run something` and have it use the underlying 32-bit node correctly.

**Describe alternatives you've considered**

No alternatives really came to my mind... For now I use a different computer with the 32-bit installation of node... This other computer is also a 64-bit computer, but I've installed the 32-bit version of node on it.

**Can you submit a pull request?**

No

-----------

Thank you very much for this great package :)

**Comment by papb** [comment]
I have just figured out a workaround for me!

* Run `nve SPECIFIC_VERSION node -p 'process.arch'` just to make it download it and put it in it's internal cache folder. The command will return `x64`
* Figure out what is its cache folder with [global-cache-dir](https://github.com/ehmicky/global-cache-dir) via `await globalCacheDir('nve')`
* Replace the `SPECIFIC_VERSION/node.exe` there with a manually downloaded 32bit node.
* Run `nve SPECIFIC_VERSION node -p 'process.arch'` again, it now returns `ia32`!

**Comment by ehmicky** [comment]
Hi @papb,

This sounds like a good idea. 

I've transferred the issue to `get-node` which is the underlying library that fetches the Node.js binary inside `nve`. 

Node.js distributes binaries according to a combination of `process.arch` and `process.platform` (see [here](https://github.com/ehmicky/get-node/blob/master/src/arch.js)). At the moment, this is not configurable and re-uses the current machine's CPU and OS. A `--platform` CLI flag should be added to allow users to choose this.

I will work on this as soon as I can.

Now I am not completely sure whether this be easy to backport to `nve@9`. Can you confirm upgrading from Node `10.13.0` to `10.17.0` is not an option?

**Comment by papb** [comment]
Hi @ehmicky, thank you very much for the fast response!

Upgrading my installed node version is doable but unfortunately quite nontrivial due to company issues. Perhaps I can work around it by using `nve@8.3.0` to use node 12 to, in turn, call `nve@9`? It will be fun :)

**Comment by papb** [comment]
If you want, I think you can implement the change in `nve@9` only. Silly company issues definitely do not justify you doing double work. You should do it in `nve@9` and I will make an effort to upgrade my node. In the meantime I can proceed with my workaround... Thanks!

**Comment by ehmicky** [comment]
I have just added the [`--arch` CLI flag](https://github.com/ehmicky/nve#--arch) to [`nve@9.1.1`](https://github.com/ehmicky/nve/releases/tag/9.1.1).

```
$ nve --arch=x32 node -p 'process.arch'
```

This is not backported, i.e. only in `nve@9` as you suggested.

Please let me know if there is any issue with the CLI flag!

**Comment by papb** [comment]
Thank you!!
